language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7 
            - ppa:george-edison55/cmake-3.x
          packages:
            - g++-6
            - clang-3.7
            - llvm-3.7-runtime
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - cmake-data
            - gdb
      env:
        - COMPILER="clang++-3.7"
        - SANITIZE=true
      before_script:
        - wget http://llvm.org/releases/3.7.1/clang+llvm-3.7.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz
        - tar -xvf clang+llvm-3.7.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz
        - sudo cp -n clang+llvm-3.7.1-x86_64-linux-gnu-ubuntu-14.04/lib/clang/3.7.1/lib/linux/*.a /usr/lib/llvm-3.7/lib/clang/3.7.1/lib/linux/
        - CXX=${COMPILER}  ./check_errors.sh
        - mkdir build && cd build
        - CXX=${COMPILER} cmake -DCMAKE_BUILD_TYPE=Debug -DTRAVIS_JOB_ID='${TRAVIS_JOB_ID}' -DSANITIZE=${SANITIZE} ..
        - make VERBOSE=1 self_test kcov

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
            - ppa:george-edison55/cmake-3.x
          packages:
            - g++-6
            - clang-3.8
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - cmake-data
            - gdb
      env:
        - COMPILER="clang++-3.8"
        - SANITIZE=true

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
            - ppa:george-edison55/cmake-3.x
          packages:
            - g++-6
            - clang-3.9
            - llvm-3.9-runtime
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - cmake-data
            - gdb
      env:
        - COMPILER="clang++-3.9"
        - SANITIZE=true

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ppa:george-edison55/cmake-3.x
          packages:
            - g++-4.9
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - cmake-data
            - gdb
      env:
        - COMPILER="g++-4.9"
        - SANITIZE=true

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ppa:george-edison55/cmake-3.x
          packages:
            - g++-5
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - cmake-data
            - gdb
      env:
        - COMPILER="g++-5"
        - SANITIZE=true

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ppa:george-edison55/cmake-3.x
          packages:
            - g++-6
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - cmake-data
            - gdb
      env:
        - COMPILER="g++-6"
        - SANITIZE=true

before_script:
  - CXX=${COMPILER}  ./check_errors.sh
  - mkdir build && cd build
  - CXX=${COMPILER} cmake -DCMAKE_BUILD_TYPE=Debug -DTRAVIS_JOB_ID='${TRAVIS_JOB_ID}' -DSANITIZE=${SANITIZE} ..
  - make VERBOSE=1 self_test kcov

script:
  make run_self_test

after_success:
  make VERBOSE=1 run_coverage
