language: cpp
sudo: required
dist: trusty

matrix:
  include:

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ppa:george-edison55/cmake-3.x
          packages:
            - g++-4.9
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - cmake-data
            - gdb
      env:
        - COMPILER=g++-4.9
        - SANITIZE=true

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ppa:george-edison55/cmake-3.x
          packages:
            - g++-5
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - cmake-data
            - gdb
      env:
        - COMPILER=g++-5
        - SANITIZE=true

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ppa:george-edison55/cmake-3.x
          packages:
            - g++-6
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - cmake-data
            - gdb
      env:
        - COMPILER=g++-6
        - SANITIZE=true

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ppa:george-edison55/cmake-3.x
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-precise-3.7 main"
              key_url : "http://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-3.7
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - cmake-date
            - gdb
      env:
        - COMPILER=clang++-3.7
        - SANITIZE=true

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ppa:george-edison55/cmake-3.x
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-precise-3.8 main"
              key_url : "http://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-3.8
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - cmake-date
            - gdb
      env:
        - COMPILER=clang++-3.8
        - SANITIZE=true

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ppa:george-edison55/cmake-3.x
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-precise-3.9 main"
              key_url : "http://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-3.9
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - cmake-date
            - gdb
      env:
        - COMPILER=clang++-3.9
        - SANITIZE=true

before_script:
  - CXX=${COMPILER}  ./check_errors.sh
  - mkdir build && cd build
  - CXX=${COMPILER} cmake -DCMAKE_BUILD_TYPE=Debug -DTRAVIS_JOB_ID='${TRAVIS_JOB_ID}' -DSANITIZE=${SANITIZE} ..
  - make VERBOSE=1 self_test kcov

script:
  make run_self_test

after_success:
  make VERBOSE=1 run_coverage
