language: cpp

matrix:
  include:

    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: ['catch', 'g++-4.9']
      env: COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: ['catch', 'g++-5']
      env: COMPILER=g++-5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-precise-3.5']
          packages: ['catch', 'clang-3.5']
      env: COMPILER=clang++-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-precise-3.6']
          packages: ['catch', 'clang-3.6']
      env: COMPILER=clang++-3.6

# Activate when 3.7 is released and the repository is available
#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          sources: ['llvm-toolchain-precise-3.7']
#          packages: ['catch', 'clang-3.7']
#      env: COMPILER=clang++-3.7

# Activate when we are allowed to use MacOS X
#    - os: osx
#      compiler: clang
#      env: COMPILER=clang++

script:
  make CXX=$COMPILER CXXFLAGS=-std=c++14 -f Makefile.travis -j3
