language: cpp

matrix:
  include:

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'libcurl4-openssl-dev', 'libelf-dev', 'libdw-dev', 'cmake', 'gdb']
      env: COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'libcurl4-openssl-dev', 'libelf-dev', 'libdw-dev', 'cmake', 'gdb']
      env: COMPILER=g++-5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6', 'libcurl4-openssl-dev', 'libelf-dev', 'libdw-dev', 'cmake', 'gdb']
      env: COMPILER=clang++-3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7', 'libcurl4-openssl-dev', 'libelf-dev', 'libdw-dev', 'cmake', 'gdb']
      env: COMPILER=clang++-3.7


# Activate when we are allowed to use MacOS X
#    - os: osx
#      compiler: clang
#      env: COMPILER=clang++

before_script:
  CXX=$COMPILER  ./check_errors.sh

script:
  wget https://github.com/philsquared/Catch/archive/v1.2.1-develop.12.tar.gz &&   tar xfz v1.2.1-develop.12.tar.gz && make CXX=$COMPILER CXXFLAGS="-std=c++14 -I Catch-1.2.1-develop.12/include -ggdb" -f Makefile.travis

after_success:
  wget https://github.com/SimonKagstrom/kcov/archive/master.zip &&  unzip master.zip && mv kcov-master kcov && mkdir kcov/build && cd kcov/build && cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make && make install DESTDIR=../built && cd ../.. && ulimit -c unlimited && ./kcov/built/usr/local/bin/kcov --skip-solibs --include-pattern="trompeloeil.hpp" --coveralls-id=${TRAVIS_JOB_ID} ./cov ./self_test -s || gdb ./self_test `find . -name "*core*"` -ex "set pagination 0" -ex "bt" -batch
